### ISSUE TITLE
提示远程主机强迫关闭了一个现有链接

### ISSUE THREAD

**Issue by clq12** [zyimm/belle#1]
提示远程主机强迫关闭了一个现有链接

- [x]     raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

**Comment by zyimm** [comment]
应该目标服务器防止CC了，可以减少抓取的频率，试一试

**Comment by clq12** [comment]
啊这
